# Generated by Django 3.0.2 on 2020-03-12 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='企業名')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'エントリー前'), (1, '一次面接前'), (2, '二次面接前'), (3, '最終面接前'), (4, '内定'), (5, '落選')], null=True, verbose_name='ステータス')),
                ('memo', models.TextField(blank=True, default='', verbose_name='メモ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
