# Generated by Django 3.0.2 on 2020-03-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200312_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(blank=True, choices=[('エントリー前', 'エントリー前'), ('一次面接前', '一次面接前'), ('二次面接前', '二次面接前'), ('最終面接前', '最終面接前'), ('内定', '内定'), ('落選', '落選')], max_length=128, null=True, verbose_name='ステータス'),
        ),
    ]
