# Generated by Django 3.0.2 on 2020-03-15 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200312_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='deadline',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='期限'),
        ),
        migrations.AddField(
            model_name='company',
            name='next',
            field=models.CharField(blank=True, choices=[('エントリー', 'エントリー'), ('エントリーシート', 'エントリーシート'), ('Webテスト', 'Webテスト'), ('コーディングテスト', 'コーディングテスト'), ('面接日程調整', '面接日程調整')], max_length=128, null=True, verbose_name='次のステップ'),
        ),
    ]
