# Generated by Django 3.0.2 on 2020-03-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20200315_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='positions',
            field=models.CharField(blank=True, choices=[('Webエンジニア', 'Webエンジニア'), ('データサイエンティスト', 'データサイエンティスト'), ('研究開発', '研究開発'), ('営業', '営業'), ('企画', '企画'), ('マーケティング', 'マーケティング')], max_length=128, null=True, verbose_name='ポジション'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(blank=True, choices=[('エントリー前', 'エントリー前'), ('一次面接前', '一次面接前'), ('二次面接前', '二次面接前'), ('三次面接前', '三次面接前'), ('最終面接前', '最終面接前'), ('内定', '内定'), ('お祈り', 'お祈り')], max_length=128, null=True, verbose_name='ステータス'),
        ),
    ]
