# Generated by Django 3.0.2 on 2020-03-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20200315_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='positions',
            field=models.CharField(blank=True, choices=[('Webエンジニア', 'Webエンジニア'), ('データサイエンティスト', 'データサイエンティスト'), ('研究開発', '研究開発'), ('ITコンサルタント', 'ITコンサルタント'), ('営業', '営業'), ('企画', '企画'), ('マーケティング', 'マーケティング')], max_length=128, null=True, verbose_name='ポジション'),
        ),
    ]
