# Generated by Django 3.0.2 on 2020-03-15 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0007_auto_20200315_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='desire',
            field=models.CharField(blank=True, choices=[('エントリー', 'エントリー'), ('エントリーシート', 'エントリーシート'), ('Webテスト', 'Webテスト'), ('コーディングテスト', 'コーディングテスト'), ('面接日程調整', '面接日程調整')], max_length=32, null=True, verbose_name='志望度'),
        ),
        migrations.AlterField(
            model_name='company',
            name='memo',
            field=models.TextField(blank=True, default='', verbose_name='選考に関するメモ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='next',
            field=models.CharField(blank=True, choices=[('エントリー', 'エントリー'), ('エントリーシート', 'エントリーシート'), ('Webテスト', 'Webテスト'), ('コーディングテスト', 'コーディングテスト'), ('面接日程調整', '面接日程調整')], max_length=32, null=True, verbose_name='次のステップ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='position',
            field=models.CharField(blank=True, choices=[('Webエンジニア', 'Webエンジニア'), ('データサイエンティスト', 'データサイエンティスト'), ('研究開発', '研究開発'), ('ITコンサルタント', 'ITコンサルタント'), ('営業', '営業'), ('企画', '企画'), ('マーケティング', 'マーケティング')], max_length=32, null=True, verbose_name='ポジション'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(blank=True, choices=[('エントリー前', 'エントリー前'), ('一次面接前', '一次面接前'), ('二次面接前', '二次面接前'), ('三次面接前', '三次面接前'), ('最終面接前', '最終面接前'), ('内定', '内定'), ('お祈り', 'お祈り')], max_length=32, null=True, verbose_name='ステータス'),
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='従業員数')),
                ('memo', models.TextField(blank=True, default='', verbose_name='メモ')),
                ('my_status', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='company.Company', verbose_name='選考状況')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
