# Generated by Django 3.0.2 on 2020-03-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20200316_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='desire',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=32, null=True, verbose_name='志望度'),
        ),
    ]
