# Generated by Django 3.0.2 on 2020-03-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20200316_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='official',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='正式名称'),
        ),
        migrations.AlterField(
            model_name='company',
            name='next',
            field=models.CharField(blank=True, choices=[('エントリー', 'エントリー'), ('エントリーシート', 'エントリーシート'), ('Webテスト', 'Webテスト'), ('コーディングテスト', 'コーディングテスト'), ('面接日程調整', '面接日程調整'), ('内定承諾', '内定承諾')], max_length=32, null=True, verbose_name='次のステップ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(blank=True, choices=[('オンライン面談前', 'オンライン面談前'), ('エントリー前', 'エントリー前'), ('一次面接前', '一次面接前'), ('二次面接前', '二次面接前'), ('三次面接前', '三次面接前'), ('最終面接前', '最終面接前'), ('内定', '内定'), ('お祈り', 'お祈り')], max_length=32, null=True, verbose_name='ステータス'),
        ),
    ]
