# Generated by Django 3.0.2 on 2020-03-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20200316_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='position',
            field=models.CharField(blank=True, choices=[('Webエンジニア', 'Webエンジニア'), ('データサイエンティスト', 'データサイエンティスト'), ('研究開発', '研究開発'), ('ITコンサルタント', 'ITコンサルタント'), ('システムエンジニア', 'システムエンジニア'), ('営業', '営業'), ('企画', '企画'), ('マーケティング', 'マーケティング')], max_length=32, null=True, verbose_name='ポジション'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='total',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='給与'),
        ),
    ]
