# Generated by Django 3.0.2 on 2020-03-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20200317_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='next',
            field=models.CharField(blank=True, choices=[('エントリー', 'エントリー'), ('エントリーシート', 'エントリーシート'), ('Webテスト', 'Webテスト'), ('コーディングテスト', 'コーディングテスト'), ('一次面接', '一次面接'), ('二次面接', '二次面接'), ('三次面接', '三次面接'), ('最終面接', '最終面接'), ('面接日程調整', '面接日程調整'), ('内定承諾', '内定承諾')], max_length=32, null=True, verbose_name='次のステップ'),
        ),
    ]
