# Generated by Django 3.0.2 on 2020-03-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_auto_20200318_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='reason',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='志望理由'),
        ),
    ]
