# Generated by Django 3.0.2 on 2020-03-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_companyinfo_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='industry',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='業界'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='vision',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='ビジョン'),
        ),
    ]
