# Generated by Django 3.0.2 on 2020-03-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_auto_20200321_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='志望理由'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='vision',
            field=models.TextField(blank=True, null=True, verbose_name='ビジョン'),
        ),
    ]
