# Generated by Django 3.0.2 on 2020-04-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_auto_20200404_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='next',
            field=models.CharField(blank=True, choices=[('説明会', '説明会'), ('エントリー', 'エントリー'), ('レポート', 'レポート'), ('スライド', 'スライド'), ('エントリーシート', 'エントリーシート'), ('Webテスト', 'Webテスト'), ('コーディングテスト', 'コーディングテスト'), ('面談', '面談'), ('一次面接', '一次面接'), ('二次面接', '二次面接'), ('三次面接', '三次面接'), ('最終面接', '最終面接'), ('日程調整', '日程調整'), ('辞退', '辞退'), ('内定承諾', '内定承諾')], max_length=32, null=True, verbose_name='次のステップ'),
        ),
    ]
