# Generated by Django 3.0.2 on 2020-04-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_auto_20200404_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='benefit',
            field=models.TextField(blank=True, null=True, verbose_name='福利厚生'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='place',
            field=models.TextField(blank=True, null=True, verbose_name='勤務地'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='working_time',
            field=models.TextField(blank=True, null=True, verbose_name='勤務時間'),
        ),
    ]
