# Generated by Django 3.0.2 on 2020-04-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_auto_20200407_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='area',
            field=models.TextField(blank=True, null=True, verbose_name='事業領域'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='specification',
            field=models.TextField(blank=True, null=True, verbose_name='特徴'),
        ),
    ]
