# Generated by Django 3.0.2 on 2020-04-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_auto_20200407_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='questions',
            field=models.TextField(blank=True, null=True, verbose_name='疑問点'),
        ),
    ]
