# Generated by Django 3.0.2 on 2020-04-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_companyinfo_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='next2',
            field=models.IntegerField(blank=True, choices=[(0, '説明会'), (1, 'エントリー'), (2, 'レポート'), (3, 'スライド'), (4, 'エントリーシート'), (5, 'Webテスト'), (6, 'コーディングテスト'), (7, '面談'), (8, '一次面接'), (9, '二次面接'), (10, '三次面接'), (11, '最終面接'), (12, '日程調整'), (13, '辞退'), (14, '内定承諾'), (15, '完了')], null=True, verbose_name='次のステップ'),
        ),
        migrations.AddField(
            model_name='company',
            name='status2',
            field=models.IntegerField(blank=True, choices=[(0, '説明会前'), (1, '面談前'), (2, 'テスト前'), (3, 'エントリー前'), (4, '一次面接前'), (5, '二次面接前'), (6, '三次面接前'), (7, '最終面接前'), (8, '結果待ち'), (9, '内々定'), (10, '内定'), (11, 'お祈り'), (12, '辞退')], null=True, verbose_name='ステータス'),
        ),
    ]
