# Generated by Django 3.0.2 on 2020-04-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_auto_20200408_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='next',
        ),
        migrations.RemoveField(
            model_name='company',
            name='status',
        ),
    ]
