# Generated by Django 3.0.2 on 2020-04-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_auto_20200408_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='next2',
            new_name='next',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='status2',
            new_name='status',
        ),
    ]
