# Generated by Django 3.0.2 on 2020-04-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_auto_20200408_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(blank=True, choices=[('0. 結果待ち', '結果待ち'), ('1. 説明会前', '説明会前'), ('2. カジュアル面談前', 'カジュアル面談前'), ('3. エントリー前', 'エントリー前'), ('4. テスト前', 'テスト前'), ('5. 一次面接前', '一次面接前'), ('6. 二次面接前', '二次面接前'), ('7. 三次面接前', '三次面接前'), ('8. 最終面接前', '最終面接前'), ('9. 内々定', '内々定'), ('10. オファー面談前', 'オファー面談前'), ('11. 内定', '内定'), ('12. お祈り', 'お祈り'), ('13. 辞退', '辞退')], max_length=32, null=True, verbose_name='ステータス'),
        ),
    ]
