# Generated by Django 3.0.2 on 2020-04-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0034_auto_20200408_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='next',
            field=models.CharField(blank=True, choices=[('0. 日程調整', '日程調整'), ('1. 説明会', '説明会'), ('2. エントリー', 'エントリー'), ('3. レポート', 'レポート'), ('4. エントリーシート', 'エントリーシート'), ('5. Webテスト', 'Webテスト'), ('6. コーディングテスト', 'コーディングテスト'), ('7. 面談準備', '面談準備'), ('8. 面接準備', '面接準備'), ('9. 内定承諾', '内定承諾'), ('10. 辞退', '辞退'), ('11. 完了', '完了')], max_length=32, null=True, verbose_name='次のステップ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(blank=True, choices=[('0. 結果待ち', '結果待ち'), ('1. 説明会前', '説明会前'), ('2. カジュアル面談前', 'カジュアル面談前'), ('3. エントリー前', 'エントリー前'), ('4. エントリー後', 'エントリー後'), ('5. テスト通過', 'テスト通過'), ('6. 一次面接通過', '一次面接通過'), ('7. 二次面接通過', '二次面接通過'), ('8. 三次面接通過', '三次面接通過'), ('9. 内々定', '内々定'), ('10. 内定', '内定'), ('11. お祈り', 'お祈り'), ('12. 辞退済', '辞退済')], max_length=32, null=True, verbose_name='ステータス'),
        ),
    ]
