# Generated by Django 3.0.2 on 2020-04-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0036_auto_20200408_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='next',
            field=models.CharField(blank=True, choices=[('00. 日程調整', '日程調整'), ('01. 説明会', '説明会'), ('02. エントリー', 'エントリー'), ('03. レポート', 'レポート'), ('04. エントリーシート', 'エントリーシート'), ('05. Webテスト', 'Webテスト'), ('06. コーディングテスト', 'コーディングテスト'), ('07. 面談準備', '面談準備'), ('08. 面接準備', '面接準備'), ('09. 内定承諾', '内定承諾'), ('10. 辞退', '辞退'), ('11. 完了', '完了')], max_length=32, null=True, verbose_name='次のステップ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(blank=True, choices=[('00. 結果待ち', '結果待ち'), ('01. 説明会後', '説明会後'), ('02. カジュアル面談後', 'カジュアル面談後'), ('03. エントリー前', 'エントリー前'), ('04. エントリー後', 'エントリー後'), ('05. テスト通過', 'テスト通過'), ('06. 一次面接通過', '一次面接通過'), ('07. 二次面接通過', '二次面接通過'), ('08. 三次面接通過', '三次面接通過'), ('09. 内々定', '内々定'), ('10. 内定', '内定'), ('11. お祈り', 'お祈り'), ('12. 辞退済', '辞退済')], max_length=32, null=True, verbose_name='ステータス'),
        ),
    ]
